name: Release Drafter

on:
  push:
    branches:
      - main
    paths:
      - 'nodejs-test/*'

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      type_breaking: 'type: breaking'
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Get PR labels as env variable
        run: echo "labels=$(gh pr list --search $COMMIT_SHA --state merged --json labels --jq '.[] | .labels[].name' | tr '\n' ',')" >> $GITHUB_ENV
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          prerelease_bool: ${{ contains(env.labels, env.type_breaking) }}
        with:
          prerelease: ${{ env.prerelease_bool }}
          prerelease-identifier: 'beta'
        
          